# Generated by Django 4.1 on 2022-08-30 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Ім'я")),
                ('position', models.CharField(max_length=255, verbose_name='Посада')),
                ('photo', models.ImageField(null=True, upload_to='photos/employees/%Y/%m/%d', verbose_name='Фото')),
                ('facebook', models.CharField(max_length=255, unique=True)),
                ('twitter', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Працівник',
                'verbose_name_plural': 'Працівники',
                'ordering': ['name', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name="Ім'я")),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('text', models.TextField(verbose_name='Опис')),
                ('status', models.CharField(choices=[('A', 'accepted'), ('C', 'considered'), ('NC', 'not considered')], db_index=True, default='A', max_length=255, verbose_name='Статус')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Час створення')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Час оновлення')),
            ],
            options={
                'verbose_name': 'Повідомлення',
                'verbose_name_plural': 'Повідомлення',
                'ordering': ['name', 'email', 'status', 'time_create', 'time_update'],
            },
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Ціна')),
                ('tilda', models.BooleanField()),
                ('word_press', models.BooleanField()),
                ('open_cart', models.BooleanField()),
                ('custom_development', models.BooleanField()),
                ('google_analytics', models.BooleanField()),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Час створення')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Час оновлення')),
            ],
            options={
                'verbose_name': 'Ціноутворення',
                'verbose_name_plural': 'Ціноутворення',
                'ordering': ['name', 'tilda', 'word_press', 'open_cart', 'custom_development', 'google_analytics', 'time_create', 'time_update'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Назва')),
                ('description', models.TextField(verbose_name='Опис')),
                ('photo', models.ImageField(null=True, upload_to='photos/services/%Y/%m/%d', verbose_name='Фото')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Час створення')),
            ],
            options={
                'verbose_name': 'Послуга',
                'verbose_name_plural': 'Послуги',
                'ordering': ['name', 'time_create'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name="Ім'я")),
                ('is_client', models.BooleanField(default=False, verbose_name='Чи клієнт')),
                ('photo', models.ImageField(null=True, upload_to='photos/users/%Y/%m/%d', verbose_name='Фото')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Час Реєстрації')),
            ],
            options={
                'verbose_name': 'Користувач',
                'verbose_name_plural': 'Користувачі',
                'ordering': ['name', 'is_client', 'time_create'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Відгук')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Час створення')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='triangle.user')),
            ],
            options={
                'verbose_name': 'Коментар',
                'verbose_name_plural': 'Коментарі',
                'ordering': ['time_create'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255, verbose_name='Коментар')),
                ('status', models.CharField(choices=[('A', 'accepted'), ('P', 'performed'), ('D', 'done'), ('De', 'denied'), ('ND', 'not done')], db_index=True, default='A', max_length=255, verbose_name='Статус')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Час створення')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Час оновлення')),
                ('time_done', models.DateTimeField(default=None, null=True, verbose_name='Час виконання')),
                ('pricing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='triangle.pricing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='triangle.user')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ['status', 'time_create', 'time_update', 'time_done'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Коментар')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Час створення')),
                ('answers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='triangle.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='triangle.user')),
            ],
            options={
                'verbose_name': 'Коментар',
                'verbose_name_plural': 'Коментарі',
                'ordering': ['time_create'],
            },
        ),
    ]
