# Generated by Django 4.1 on 2022-08-30 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triangle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='answers',
        ),
        migrations.AddField(
            model_name='comment',
            name='answer_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='triangle.comment'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='price',
            field=models.FloatField(verbose_name='Ціна'),
        ),
    ]
