# Generated by Django 4.1 on 2022-08-31 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triangle', '0003_section_skill_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='URL')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Час публікації')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ['slug', 'name', 'time_create'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='URL')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Час публікації')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['slug', 'name', 'time_create'],
            },
        ),
        migrations.AlterField(
            model_name='comment',
            name='answer_to',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='triangle.comment'),
        ),
        migrations.AlterField(
            model_name='project',
            name='projects',
            field=models.ManyToManyField(to='triangle.project'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='URL')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('description', models.TextField(verbose_name='Опис')),
                ('photo', models.ImageField(null=True, upload_to='photos/posts/%Y/%m/%d', verbose_name='Фото')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Лайки')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Час публікації')),
                ('categories', models.ManyToManyField(to='triangle.category')),
                ('tags', models.ManyToManyField(to='triangle.tag')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Пости',
                'ordering': ['slug', 'name', 'likes', 'time_create'],
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='triangle.post'),
        ),
    ]
