# Generated by Django 4.1 on 2022-08-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triangle', '0005_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/projects/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='skill',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/skills/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/employees/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/posts/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='service',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/services/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/users/', verbose_name='Фото'),
        ),
    ]
