# Generated by Django 4.1 on 2022-09-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triangle', '0007_alter_category_name_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
        migrations.AddField(
            model_name='project',
            name='photo_big',
            field=models.ImageField(null=True, upload_to='photos/projects/big/', verbose_name='Велике фото'),
        ),
        migrations.AddField(
            model_name='project',
            name='photo_small',
            field=models.ImageField(null=True, upload_to='photos/projects/small/', verbose_name='Маленьке фото'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo_big',
            field=models.ImageField(null=True, upload_to='photos/users/big/', verbose_name='Велике фото'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo_small',
            field=models.ImageField(null=True, upload_to='photos/users/small/', verbose_name='Маленьке фото'),
        ),
    ]
