# Generated by Django 4.1 on 2022-09-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triangle', '0008_remove_project_photo_remove_skill_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='u', max_length=254),
        ),
    ]
