# Generated by Django 4.1 on 2022-09-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triangle', '0010_service_is_top_user_is_top_alter_message_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_top',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
