# Generated by Django 4.1 on 2022-09-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triangle', '0011_project_is_top_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='1111', max_length=255, verbose_name='Пароль'),
        ),
    ]
