# Generated by Django 4.1 on 2022-09-21 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triangle', '0012_user_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='response',
            options={'ordering': ['time_create'], 'verbose_name': 'Відгук', 'verbose_name_plural': 'Відгуки'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='answer_to',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='triangle.comment', verbose_name='Відповідь на'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='triangle.post', verbose_name='Пост'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='triangle.user', verbose_name='Користувач'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pricing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='triangle.pricing', verbose_name='Ціоноутворення'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='triangle.user', verbose_name='Користувач'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255, verbose_name='Пароль'),
        ),
    ]
